patch_runtimeRTM: Updating printf calls
Adding patches for dotnet/runtime cross build in runtimeRTM patch

- eng/native/gen-buildsys.sh: Ensuring "\n" is interpreted as newline
  by passing to bash printf.

  The patched script is used during the initial CMake tooling, may be
  applied during a rebuild of a dotnet/runtime source. The script might
  not be used during a build from a clean source tree

- src/coreclr/pal/tools/gen-dactable-rva.sh: Encoding output with
  hexidecimal format

  This may serve to resolve the following build failure under
  cross-build for FreeBSD:

~~~~
  /usr/local/src/dotsys_wk/crossbuild/build/runtime/src/coreclr/debug/daccess/daccess.cpp:7264:38: error: invalid suffix 'x' on integer constant
      *dacTableAddress = baseAddress + DAC_TABLE_RVA;
                                       ^
  /usr/local/src/dotsys_wk/crossbuild/build/runtime/artifacts/obj/coreclr/FreeBSD.x64.Release/inc/dactablerva.h:1:24: note: expanded from macro 'DAC_TABLE_RVA'
  #define DAC_TABLE_RVA 0x          6c0df8
                         ^
  1 error generated.
~~~~

In the amended patch, the git index information has been produced from
a local Git branch build/v6.0.3 on the dotnet/runtime source tag v6.0.3

(cherry picked from commit e42671f7c1e699da4955ea9fc6f57f41c6391ffc)